### ISSUE TITLE
not found able to access on server

### ISSUE THREAD

**Issue by ajayphp** [leda-ferreira/yii2-app-basic-admin-lte#1]
Hi,
Thx. for creating admintLTE with app,

It run fine with local server,
but on vps i installed with same composer ,

but i http://domain/basic/web/site/login

The requested URL /basic/web/site/login/ was not found on this server.

what could be the reason.

resolved , was new server and enabled mod_rewrite

-- how to direct launch in same directory ,rather web/

**Comment by leda-ferreira** [comment]
You need to point your virtual host root directory to the web folder. I often do it like this: 
- navigate to your server webroot
- cd up one directory above your webroot
- `mv public_html _public_html`
- `ln -s /path/to/yii/web public_html`

Replace `public_html` with the webroot folder name.
Another option is to update your virtual host configuration file and specify the web folder as the webroot.
 Good luck ;)
