### ISSUE TITLE
user login and signup - database

### ISSUE THREAD

**Issue by ajayphp** [leda-ferreira/yii2-app-basic-admin-lte#2]
Hi,

How can i user login and signup using database. 
as there is also not user migration etc, 

please guide me how to implement this.

**Comment by leda-ferreira** [comment]
The basic app template doesn't include user migration.
But you can find an example of how to implement one in the [advanced template](https://github.com/yiisoft/yii2-app-advanced/blob/master/console/migrations/m130524_201442_init.php).
Here is a [good tutorial](http://www.yiiframework.com/doc-2.0/guide-db-migrations.html) on how to implement migrations. It can give you some idea on how to adapt the example on the previous link.
If you need further assistance, please let me know :-)
